version: '3.8'

services:
  app:
    build:
      context: .
      target: builder # On reste au stade de développement
    ports:
      - "3000:3000"
      - "9229:9229" # Port pour le debug Node.js
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://dev:dev@db:5432/mydb
    command: bun run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: